// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef source_view_tmp_h
#define source_view_tmp_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
Fl_Double_Window* make_window();
#endif
